name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & push Docker images
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./Back
          file: ./Back/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tp2-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./Front
          file: ./Front/Dockerfile
          push: true
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tp2-frontend:latest
